name: myeyes
description: "视途无忧 - 视障人士辅助应用"
publish_to: 'none' # 防止意外发布到 pub.dev
version: 1.0.0+1 # 版本号格式: major.minor.patch+build_number

environment:
  sdk: '>=3.2.5 <4.0.0' # Flutter SDK版本要求

dependencies:
  #flutter_lifecycle_detector: ^0.0.6  # 应用生命周期检测
  network_info_plus: ^6.1.3          # 网络信息获取
  volume_control: ^0.1.5             # 音量控制
  app_settings: ^5.1.1               # 系统设置跳转
  permission_handler: ^11.4.0        # 权限管理
  #path_provider: ^2.1.2              # 文件路径管理
  flutter_tts: ^4.2.2               # 文字转语音
  image_picker: ^1.1.2              # 图片选择器
  flutter_vision: ^1.1.4            # YOLOv5目标检测
  flutter:
    sdk: flutter
  geolocator: ^13.0.2               # 地理位置服务
  dio: ^5.4.0                       # 网络请求客户端
  http: ^1.1.0                      # HTTP请求
  cupertino_icons: ^1.0.2           # iOS风格图标 
  amap_map: ^1.0.15                  # 使用确切版本号
  openai_dart: ^0.4.5
  
  opencv_dart: ^1.4.1               # OpenCV图像处理
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2 # 用于存储隐私协议状态
  flutter_blue_plus: ^1.35.3  # 添加蓝牙通信库

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0             # 代码规范检查
  flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons配置应该在这里（与flutter:同级）
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  assets:
    - assets/                        # 通用资源目录
    - assets/tessdata/              # OCR模型数据目录
    - assets/icon/                  # 图标资源目录
  uses-material-design: true        # 使用Material Design
